[package]
name = "app"
version = "2.0.0"
description = "Free TTS application for streaming chat messages in your stream"
authors = ["Nerve"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
tokio = { version = "1", features = ["full"] }
axum = "0.7"
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }
tauri-plugin-shell = "2.3.4"
tauri-plugin-single-instance = "2.3.7"
tauri-plugin-updater = "2"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15"
hex = "0.4"
rand = "0.8"
keyring = { version = "3", features = ["windows-native", "apple-native", "sync-secret-service"] }
