use axum::{
    extract::{Query, State},
    http::{StatusCode, HeaderMap, header::ORIGIN},
    response::{Html, IntoResponse},
    routing::{get, post},
    Router,
    Json,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::net::SocketAddr;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use tauri::State as TauriState;
use tokio::net::TcpListener;
use tokio::sync::broadcast;
use tokio::sync::RwLock;
use hmac::{Hmac, Mac};
use sha1::Sha1;
use sha2::Sha256;

use crate::alerts::{AlertPayload, TwitchEventSubPayload, process_twitch_event, process_youtube_alert};

type HmacSha256 = Hmac<Sha256>;
type HmacSha1 = Hmac<Sha1>;

fn get_youtube_client_id() -> Result<String, String> {
    std::env::var("YOUTUBE_CLIENT_ID")
        .map_err(|_| "YOUTUBE_CLIENT_ID environment variable is required".to_string())
}

fn get_youtube_client_secret() -> Option<String> {
    std::env::var("YOUTUBE_CLIENT_SECRET").ok()
}

fn get_twitch_client_id() -> Result<String, String> {
    std::env::var("TWITCH_CLIENT_ID")
        .or_else(|_| std::env::var("VITE_TWITCH_CLIENT_ID"))
        .map_err(|_| "TWITCH_CLIENT_ID environment variable is required".to_string())
}

fn get_twitch_client_secret() -> Option<String> {
    std::env::var("TWITCH_CLIENT_SECRET").ok()
}

fn is_youtube_auth_configured() -> bool {
    get_youtube_client_secret().is_some()
}

const REDIRECT_URI: &str = "http://localhost:3000/callback";
const MAX_REQUESTS_PER_MINUTE: u32 = 30;
/// Timestamp skew window for Twitch EventSub signatures; deliveries outside
/// it are treated as replays.
const EVENTSUB_MAX_SKEW_SECS: i64 = 600;

/// Set once the loopback server has successfully bound its port. Auth flows
/// refuse to start (and send the user to the browser) while it is down.
static CALLBACK_SERVER_READY: AtomicBool = AtomicBool::new(false);

/// A state value generated by the webview and registered through the
/// `oauth_begin` command before the provider flow starts. The loopback
/// callback server consumes each entry exactly once. `code_verifier` carries
/// the PKCE verifier for authorization-code flows; it never travels through
/// the browser.
#[derive(Debug, Clone)]
pub struct OAuthStateEntry {
    pub service: String,
    pub created_at: u64,
    pub code_verifier: Option<String>,
}

pub type OAuthStateStore = Arc<RwLock<HashMap<String, OAuthStateEntry>>>;

const OAUTH_STATE_EXPIRY_SECS: u64 = 600;

fn now_secs() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs()
}

#[derive(Debug, Clone, Deserialize)]
pub struct OAuthCallback {
    pub token: String,
    pub service: String,
    pub error: Option<String>,
    pub refresh_token: Option<String>,
    pub expires_in: Option<i64>,
    pub state: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct TokenExchangeRequest {
    pub code: String,
    pub state: String,
}

#[derive(Debug, Clone, Deserialize)]
pub struct AuthCompleteRequest {
    pub token: String,
    pub service: String,
    pub error: Option<String>,
    pub refresh_token: Option<String>,
    pub expires_in: Option<i64>,
    pub state: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TokenResponse {
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub expires_in: i64,
    pub token_type: String,
}

/// Serialized rejection value for Tauri commands; the frontend switches on
/// `kind` to decide between clearing tokens and retrying.
#[derive(Debug, Serialize)]
#[serde(tag = "kind", content = "message", rename_all = "snake_case")]
pub enum CommandError {
    NotConfigured(String),
    Network(String),
    BadResponse(String),
    InvalidGrant(String),
    InvalidClient(String),
}

#[tauri::command]
pub fn oauth_redirect_uri() -> &'static str {
    REDIRECT_URI
}

#[tauri::command]
pub async fn oauth_begin(
    service: String,
    state: String,
    code_verifier: Option<String>,
    states: TauriState<'_, OAuthStateStore>,
) -> Result<(), String> {
    if service != "twitch" && service != "youtube" {
        return Err("unsupported OAuth service".to_string());
    }
    if state.len() < 16 {
        return Err("state is too short".to_string());
    }
    if !CALLBACK_SERVER_READY.load(Ordering::Acquire) {
        return Err("Login server is not running. Please restart StreamTTS and try again.".to_string());
    }

    let mut map = states.write().await;
    let now = now_secs();
    map.retain(|_, entry| now.saturating_sub(entry.created_at) < OAUTH_STATE_EXPIRY_SECS);
    map.insert(state, OAuthStateEntry {
        service,
        created_at: now,
        code_verifier,
    });
    Ok(())
}

/// Single-use state consumption: removes the entry and requires it to be
/// unexpired. Callers are responsible for checking `service`.
async fn consume_state(states: &OAuthStateStore, state: &str) -> Option<OAuthStateEntry> {
    let mut map = states.write().await;
    map.remove(state).filter(|entry| {
        now_secs().saturating_sub(entry.created_at) <= OAUTH_STATE_EXPIRY_SECS
    })
}

#[derive(Clone)]
struct OAuthServerState {
    sender: broadcast::Sender<OAuthCallback>,
    alert_sender: broadcast::Sender<AlertPayload>,
    rate_limiter: Arc<RwLock<RateLimiter>>,
    oauth_states: OAuthStateStore,
    twitch_eventsub_secret: String,
    youtube_hub_secret: String,
}

#[derive(Clone)]
struct RateLimiter {
    requests: HashMap<String, Vec<u64>>,
}

impl RateLimiter {
    fn new() -> Self {
        RateLimiter {
            requests: HashMap::new(),
        }
    }

    fn check_and_record(&mut self, client_ip: &str) -> bool {
        let now = now_secs();

        let window_start = now.saturating_sub(60);

        let entry = self.requests.entry(client_ip.to_string()).or_insert_with(Vec::new);
        entry.retain(|&timestamp| timestamp > window_start);

        if entry.len() >= MAX_REQUESTS_PER_MINUTE as usize {
            return false;
        }

        entry.push(now);
        true
    }
}

/// Constant-time equality over hex strings of equal length.
fn constant_time_eq(a: &str, b: &str) -> bool {
    if a.len() != b.len() {
        return false;
    }
    a.bytes().zip(b.bytes()).fold(0u8, |acc, (x, y)| acc | (x ^ y)) == 0
}

/// Reject deliveries whose timestamp drifts beyond the replay window.
fn eventsub_timestamp_fresh(timestamp: &str) -> bool {
    match chrono::DateTime::parse_from_rfc3339(timestamp) {
        Ok(parsed) => (now_secs() as i64 - parsed.timestamp()).abs() <= EVENTSUB_MAX_SKEW_SECS,
        Err(_) => false,
    }
}

/// Verify Twitch EventSub message signature against the per-install secret.
fn verify_twitch_signature(headers: &HeaderMap, body: &str, secret: &str) -> bool {
    let message_id = headers.get("Twitch-Eventsub-Message-Id")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    let timestamp = headers.get("Twitch-Eventsub-Message-Timestamp")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    let signature = headers.get("Twitch-Eventsub-Message-Signature")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");

    if message_id.is_empty() || timestamp.is_empty() || signature.is_empty() {
        return false;
    }

    if !eventsub_timestamp_fresh(timestamp) {
        log::warn!("Twitch EventSub delivery outside timestamp window - rejecting possible replay");
        return false;
    }

    let message = format!("{}{}{}", message_id, timestamp, body);

    let mut mac = match HmacSha256::new_from_slice(secret.as_bytes()) {
        Ok(mac) => mac,
        Err(_) => return false,
    };

    mac.update(message.as_bytes());
    let expected = format!("sha256={}", hex::encode(mac.finalize().into_bytes()));

    constant_time_eq(&expected, signature)
}

/// Verify a PubSubHubbub/Websub delivery signed with the per-install hub
/// secret. Accepts both sha1 (PubSubHubbub 0.4) and sha256 (Websub) forms.
fn verify_hub_signature(headers: &HeaderMap, body: &str, secret: &str) -> bool {
    let signature = headers.get("X-Hub-Signature")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");
    if signature.is_empty() {
        return false;
    }

    let Some((algo, sig)) = signature.split_once('=') else {
        return false;
    };

    let computed = match algo {
        "sha1" => {
            let Ok(mut mac) = HmacSha1::new_from_slice(secret.as_bytes()) else { return false };
            mac.update(body.as_bytes());
            hex::encode(mac.finalize().into_bytes())
        }
        "sha256" => {
            let Ok(mut mac) = HmacSha256::new_from_slice(secret.as_bytes()) else { return false };
            mac.update(body.as_bytes());
            hex::encode(mac.finalize().into_bytes())
        }
        _ => return false,
    };

    constant_time_eq(&computed, sig)
}

/// Check if origin is allowed
/// Allows known development origins OR requests without Origin header (Tauri local requests)
fn is_allowed_origin(headers: &HeaderMap) -> bool {
    let allowed = [
        "http://localhost:3000",
        "http://localhost:8080",
        "http://localhost:5173",
    ];

    if let Some(origin) = headers.get(ORIGIN).and_then(|h| h.to_str().ok()) {
        return allowed.iter().any(|&a| a == origin);
    }

    // Check for Tauri-specific header (webview local request)
    // This is a defensive check - Tauri requests typically don't send Origin
    if let Some(host) = headers.get("host").and_then(|h| h.to_str().ok()) {
        if host.starts_with("127.0.0.1:") || host.starts_with("localhost:") {
            return true;
        }
    }

    // Reject requests without origin from non-local hosts
    // This prevents CSRF from external sites
    false
}

pub async fn start_oauth_server(
    sender: broadcast::Sender<OAuthCallback>,
    alert_sender: broadcast::Sender<AlertPayload>,
    oauth_states: OAuthStateStore,
    twitch_eventsub_secret: String,
    youtube_hub_secret: String,
) -> anyhow::Result<()> {
    if !is_youtube_auth_configured() {
        log::warn!("YOUTUBE_CLIENT_SECRET not set. YouTube OAuth will return configuration errors.");
    }

    let state = Arc::new(OAuthServerState {
        sender,
        alert_sender,
        rate_limiter: Arc::new(RwLock::new(RateLimiter::new())),
        oauth_states,
        twitch_eventsub_secret,
        youtube_hub_secret,
    });
    let app = Router::new()
        .route("/callback", get(handle_callback))
        .route("/auth-complete", post(handle_auth_complete))
        .route("/auth-exchange", post(handle_auth_exchange))
        .route("/twitch-alerts", post(handle_twitch_alerts))
        .route("/youtube-alerts", get(handle_youtube_challenge).post(handle_youtube_alerts))
        .with_state(state);

    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let listener = TcpListener::bind(addr).await?;
    log::info!("OAuth server listening on {}", addr);
    CALLBACK_SERVER_READY.store(true, Ordering::Release);

    axum::serve(listener, app).await?;
    Ok(())
}

async fn check_rate_limit(state: &Arc<OAuthServerState>, client_ip: &str) -> bool {
    let mut limiter = state.rate_limiter.write().await;
    limiter.check_and_record(client_ip)
}

async fn handle_callback(Query(_params): Query<HashMap<String, String>>) -> Html<&'static str> {
    Html(include_str!("../oauth_callback.html"))
}

async fn handle_auth_complete(
    headers: HeaderMap,
    State(state): State<Arc<OAuthServerState>>,
    Json(payload): Json<AuthCompleteRequest>,
) -> impl IntoResponse {
    if !is_allowed_origin(&headers) {
        log::warn!("Rejected auth-complete from disallowed origin");
        return StatusCode::FORBIDDEN.into_response();
    }

    let client_ip = "auth-complete";
    if !check_rate_limit(&state, client_ip).await {
        return (StatusCode::TOO_MANY_REQUESTS, Json(ErrorResponse {
            error: "Rate limit exceeded. Please try again later.".to_string(),
        })).into_response();
    }

    // State is mandatory: the webview registers it via `oauth_begin` before the
    // provider flow starts, and it is consumed exactly once here. Without this,
    // any local process could inject credentials into the app.
    let Some(state_param) = payload.state.as_deref() else {
        log::warn!("auth-complete rejected: missing state parameter");
        return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
            error: "Missing OAuth state parameter".to_string(),
        })).into_response();
    };

    let Some(entry) = consume_state(&state.oauth_states, state_param).await else {
        log::warn!("Invalid or already-consumed OAuth state parameter in auth-complete");
        return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
            error: "Invalid or expired OAuth state".to_string(),
        })).into_response();
    };

    if payload.service != entry.service {
        log::warn!("auth-complete service mismatch: payload={}, registered={}", payload.service, entry.service);
        return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
            error: "Invalid or expired OAuth state".to_string(),
        })).into_response();
    }

    if payload.token.is_empty() && payload.error.is_none() {
        return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
            error: "Missing token or error in auth-complete payload".to_string(),
        })).into_response();
    }

    log::info!("Received auth complete for service: {}", payload.service);

    let callback = OAuthCallback {
        token: payload.token,
        service: entry.service,
        error: payload.error,
        refresh_token: payload.refresh_token,
        expires_in: payload.expires_in,
        state: Some(state_param.to_string()),
    };

    if let Err(e) = state.sender.send(callback) {
        log::error!("Failed to send OAuth callback: {}", e);
        return (StatusCode::INTERNAL_SERVER_ERROR, Json(ErrorResponse {
            error: "Internal server error".to_string(),
        })).into_response();
    }

    "OK".into_response()
}

/// Exchange an authorization code with Google (OAuth 2.0, PKCE when available).
async fn exchange_google_code(
    code: &str,
    code_verifier: Option<&str>,
) -> Result<ProviderTokenResponse, String> {
    let client_secret = get_youtube_client_secret().ok_or_else(|| {
        "YouTube authentication is not configured.".to_string()
    })?;
    let client_id = get_youtube_client_id()?;

    let mut params = vec![
        ("code", code.to_string()),
        ("client_id", client_id),
        ("client_secret", client_secret),
        ("redirect_uri", REDIRECT_URI.to_string()),
        ("grant_type", "authorization_code".to_string()),
    ];
    if let Some(verifier) = code_verifier {
        params.push(("code_verifier", verifier.to_string()));
    }

    let client = reqwest::Client::new();
    let response = client
        .post("https://oauth2.googleapis.com/token")
        .form(&params)
        .send()
        .await
        .map_err(|e| format!("Failed to connect to authentication provider: {e}"))?;

    if !response.status().is_success() {
        let status = response.status();
        let body: serde_json::Value = response.json().await.unwrap_or(serde_json::Value::Null);
        return Err(format!(
            "Token exchange failed with status {status}: {}",
            token_error_message(&body)
        ));
    }

    response
        .json::<ProviderTokenResponse>()
        .await
        .map_err(|e| format!("Failed to process authentication response: {e}"))
}

/// Exchange an authorization code with Twitch (PKCE; no client secret needed
/// when a code_verifier was registered for this flow).
async fn exchange_twitch_code(
    code: &str,
    code_verifier: Option<&str>,
) -> Result<ProviderTokenResponse, String> {
    let client_id = get_twitch_client_id()?;

    let mut params = vec![
        ("code", code.to_string()),
        ("client_id", client_id),
        ("redirect_uri", REDIRECT_URI.to_string()),
        ("grant_type", "authorization_code".to_string()),
    ];
    if let Some(verifier) = code_verifier {
        params.push(("code_verifier", verifier.to_string()));
    }
    if let Some(secret) = get_twitch_client_secret() {
        params.push(("client_secret", secret));
    }

    let client = reqwest::Client::new();
    let response = client
        .post("https://id.twitch.tv/oauth2/token")
        .form(&params)
        .send()
        .await
        .map_err(|e| format!("Failed to connect to authentication provider: {e}"))?;

    if !response.status().is_success() {
        let status = response.status();
        let body: serde_json::Value = response.json().await.unwrap_or(serde_json::Value::Null);
        return Err(format!(
            "Token exchange failed with status {status}: {}",
            token_error_message(&body)
        ));
    }

    response
        .json::<ProviderTokenResponse>()
        .await
        .map_err(|e| format!("Failed to process authentication response: {e}"))
}

fn token_error_message(body: &serde_json::Value) -> String {
    body["error_description"]
        .as_str()
        .or_else(|| body["message"].as_str())
        .unwrap_or("unknown error")
        .to_string()
}

async fn handle_auth_exchange(
    headers: HeaderMap,
    State(state): State<Arc<OAuthServerState>>,
    Json(payload): Json<TokenExchangeRequest>,
) -> impl IntoResponse {
    if !is_allowed_origin(&headers) {
        log::warn!("Rejected auth-exchange from disallowed origin");
        return StatusCode::FORBIDDEN.into_response();
    }

    // Consume the state before touching the network so an authorization code
    // cannot be replayed through this endpoint. The service comes from the
    // registered entry, not from the request.
    let Some(entry) = consume_state(&state.oauth_states, &payload.state).await else {
        log::warn!("Invalid or already-consumed OAuth state parameter in auth-exchange");
        return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
            error: "Invalid or expired OAuth state".to_string(),
        })).into_response();
    };

    if !check_rate_limit(&state, "auth-exchange").await {
        return (StatusCode::TOO_MANY_REQUESTS, Json(ErrorResponse {
            error: "Rate limit exceeded. Please try again later.".to_string(),
        })).into_response();
    }

    log::info!("Received auth exchange request for {}", entry.service);

    let service = entry.service.clone();
    let exchange_result = match service.as_str() {
        "youtube" => exchange_google_code(&payload.code, entry.code_verifier.as_deref()).await,
        "twitch" => exchange_twitch_code(&payload.code, entry.code_verifier.as_deref()).await,
        other => Err(format!("unsupported OAuth service '{other}'")),
    };

    let token_response = match exchange_result {
        Ok(response) => response,
        Err(message) => {
            log::error!("Token exchange failed: {}", message);
            let _ = state.sender.send(OAuthCallback {
                token: String::new(),
                service,
                error: Some("Token exchange failed. Please try again.".to_string()),
                refresh_token: None,
                expires_in: None,
                state: Some(payload.state.clone()),
            });
            return (StatusCode::BAD_REQUEST, Json(ErrorResponse {
                error: "Token exchange failed. Please try again.".to_string(),
            })).into_response();
        }
    };

    log::info!("Successfully exchanged code for tokens");

    let callback = OAuthCallback {
        token: token_response.access_token.clone(),
        service,
        error: None,
        refresh_token: token_response.refresh_token.clone(),
        expires_in: Some(token_response.expires_in),
        state: Some(payload.state.clone()),
    };

    if let Err(e) = state.sender.send(callback) {
        log::error!("Failed to send OAuth callback: {}", e);
    }

    Json(TokenResponse {
        access_token: token_response.access_token,
        refresh_token: token_response.refresh_token,
        expires_in: token_response.expires_in,
        token_type: token_response.token_type,
    }).into_response()
}

/// Refresh a YouTube access token. Runs over Tauri IPC (not HTTP) so that no
/// unauthenticated local HTTP endpoint holds the client secret pathway.
#[tauri::command]
pub async fn youtube_refresh_token(refresh_token: String) -> Result<TokenResponse, CommandError> {
    let client_secret = get_youtube_client_secret().ok_or_else(|| {
        CommandError::NotConfigured("YouTube authentication is not configured.".to_string())
    })?;
    let client_id = get_youtube_client_id()
        .map_err(CommandError::NotConfigured)?;

    let params = vec![
        ("refresh_token".to_string(), refresh_token),
        ("client_id".to_string(), client_id),
        ("client_secret".to_string(), client_secret),
        ("grant_type".to_string(), "refresh_token".to_string()),
    ];

    refresh_token_grant("https://oauth2.googleapis.com/token", &params).await
}

/// Refresh a Twitch user access token. Twitch user tokens from the
/// authorization-code flow are short-lived; without a configured
/// TWITCH_CLIENT_SECRET refresh may be rejected, in which case the frontend
/// falls back to re-authentication.
#[tauri::command]
pub async fn twitch_refresh_token(refresh_token: String) -> Result<TokenResponse, CommandError> {
    let client_id = get_twitch_client_id()
        .map_err(CommandError::NotConfigured)?;

    let mut params = vec![
        ("refresh_token".to_string(), refresh_token),
        ("client_id".to_string(), client_id),
        ("grant_type".to_string(), "refresh_token".to_string()),
    ];
    if let Some(secret) = get_twitch_client_secret() {
        params.push(("client_secret".to_string(), secret));
    }

    refresh_token_grant("https://id.twitch.tv/oauth2/token", &params).await
}

async fn refresh_token_grant(
    endpoint: &str,
    params: &[(String, String)],
) -> Result<TokenResponse, CommandError> {
    let client = reqwest::Client::new();
    let response = client
        .post(endpoint)
        .form(params)
        .send()
        .await
        .map_err(|e| CommandError::Network(format!("Failed to connect to authentication provider: {e}")))?;

    if !response.status().is_success() {
        let status = response.status();
        let body: serde_json::Value = response.json().await.unwrap_or(serde_json::Value::Null);
        let google_error = body["error"].as_str().unwrap_or("");
        let message = token_error_message(&body);

        return Err(match google_error {
            "invalid_grant" => CommandError::InvalidGrant(message),
            "invalid_client" => CommandError::InvalidClient(message),
            _ => CommandError::BadResponse(format!(
                "Token refresh failed with status {status}: {message}"
            )),
        });
    }

    let token_response: ProviderTokenResponse = response.json().await.map_err(|e| {
        CommandError::BadResponse(format!("Failed to process refresh response: {e}"))
    })?;

    Ok(TokenResponse {
        access_token: token_response.access_token,
        refresh_token: token_response.refresh_token,
        expires_in: token_response.expires_in,
        token_type: token_response.token_type,
    })
}

async fn handle_twitch_alerts(
    headers: HeaderMap,
    State(state): State<Arc<OAuthServerState>>,
    body: String,
) -> impl IntoResponse {
    let message_type = headers.get("Twitch-Eventsub-Message-Type")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("");

    match message_type {
        "webhook_callback_verification" => {
            // Verify signature for challenge requests too
            if !verify_twitch_signature(&headers, &body, &state.twitch_eventsub_secret) {
                log::warn!("Twitch EventSub verification request with invalid signature");
                return StatusCode::FORBIDDEN.into_response();
            }

            if let Ok(payload) = serde_json::from_str::<serde_json::Value>(&body) {
                let challenge = payload["challenge"].as_str().unwrap_or("");
                log::info!("Twitch EventSub verification challenge received");
                challenge.to_string().into_response()
            } else {
                StatusCode::BAD_REQUEST.into_response()
            }
        }
        "notification" => {
            // Verify Twitch EventSub signature
            if !verify_twitch_signature(&headers, &body, &state.twitch_eventsub_secret) {
                log::warn!("Twitch EventSub notification with invalid signature - rejected");
                return StatusCode::FORBIDDEN.into_response();
            }

            if let Ok(payload) = serde_json::from_str::<serde_json::Value>(&body) {
                if let Ok(twitch_payload) = serde_json::from_value::<TwitchEventSubPayload>(payload) {
                    if let Some(alert) = process_twitch_event(twitch_payload) {
                        log::info!("Twitch alert processed: {} - {}", alert.alert_type, alert.user_name);
                        let _ = state.alert_sender.send(alert);
                    }
                }
            }
            StatusCode::OK.into_response()
        }
        _ => StatusCode::OK.into_response(),
    }
}

async fn handle_youtube_challenge(
    Query(params): Query<HashMap<String, String>>,
) -> impl IntoResponse {
    if let Some(challenge) = params.get("hub.challenge") {
        log::info!("YouTube PubSubHubbub verification challenge received");
        challenge.clone().into_response()
    } else {
        StatusCode::BAD_REQUEST.into_response()
    }
}

async fn handle_youtube_alerts(
    State(state): State<Arc<OAuthServerState>>,
    headers: HeaderMap,
    body: String,
) -> impl IntoResponse {
    // PubSubHubbub/Websub deliveries are only trusted when signed with the
    // per-install hub secret (set when subscribing to the hub).
    if !verify_hub_signature(&headers, &body, &state.youtube_hub_secret) {
        log::warn!("YouTube alert delivery with missing or invalid X-Hub-Signature - rejected");
        return StatusCode::FORBIDDEN.into_response();
    }

    log::info!("Received signed YouTube alert notification");
    if let Some(alert) = process_youtube_alert(&body) {
        let _ = state.alert_sender.send(alert);
    }
    StatusCode::OK.into_response()
}

#[derive(Debug, Clone, Deserialize)]
struct ProviderTokenResponse {
    access_token: String,
    refresh_token: Option<String>,
    expires_in: i64,
    token_type: String,
}

#[derive(Debug, Clone, Serialize)]
struct ErrorResponse {
    error: String,
}
